version: '3'
services:
  api:
    container_name: fa-api
    build: .
    depends_on:
      - postgres
    ports:
      #- <port on localhost>:<port on container>
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro # ro = read only
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env

  postgres:
    container_name: fa-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
